name: EventManager
version: '${version}'

main: me.matt5262.eventManager.EventManager
api-version: '26.2'
load: POSTWORLD

depend: [ProtocolLib]
authors: [Matt_5262]

commands:
  Spawn:
    description: Teleports you to spawn.
    usage: /spawn [editor]
    aliases: []

permissions:
  eventmanager.admin.spawn:
    description: Allows players to use the /spawn editor subcommand.
    default: op